bash scripts_cp/run_array_launcher_cp_2_ackley.sh
bash scripts_cp/run_array_launcher_cp_2_diabetes.sh
bash scripts_cp/run_array_launcher_cp_2_pressure.sh
bash scripts_cp/run_array_launcher_cp_2_warcraft_1.sh
bash scripts_cp/run_array_launcher_cp_2_warcraft_2.sh

bash scripts_cp/run_array_launcher_cp_3_ackley.sh
bash scripts_cp/run_array_launcher_cp_3_diabetes.sh
bash scripts_cp/run_array_launcher_cp_3_pressure.sh
bash scripts_cp/run_array_launcher_cp_3_warcraft_1.sh
bash scripts_cp/run_array_launcher_cp_3_warcraft_2.sh

bash scripts_cp/run_array_launcher_cp_4_ackley.sh
bash scripts_cp/run_array_launcher_cp_4_diabetes.sh
bash scripts_cp/run_array_launcher_cp_4_pressure.sh
bash scripts_cp/run_array_launcher_cp_4_warcraft_1.sh
bash scripts_cp/run_array_launcher_cp_4_warcraft_2.sh

bash scripts_cp/run_array_launcher_cp_5_ackley.sh
bash scripts_cp/run_array_launcher_cp_5_diabetes.sh
bash scripts_cp/run_array_launcher_cp_5_pressure.sh
bash scripts_cp/run_array_launcher_cp_5_warcraft_1.sh
bash scripts_cp/run_array_launcher_cp_5_warcraft_2.sh

bash scripts_cp/run_array_launcher_cp_6_ackley.sh
bash scripts_cp/run_array_launcher_cp_6_diabetes.sh
bash scripts_cp/run_array_launcher_cp_6_pressure.sh
bash scripts_cp/run_array_launcher_cp_6_warcraft_1.sh
bash scripts_cp/run_array_launcher_cp_6_warcraft_2.sh