#!/bin/bash

commands=(
  "bash scripts/scripts_cp/run_array_launcher_cp_2_ackley.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_2_diabetes.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_2_pressure.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_2_warcraft_1.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_2_warcraft_2.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_3_ackley.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_3_diabetes.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_3_pressure.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_3_warcraft_1.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_3_warcraft_2.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_4_ackley.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_4_diabetes.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_4_pressure.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_4_warcraft_1.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_4_warcraft_2.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_5_ackley.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_5_diabetes.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_5_pressure.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_5_warcraft_1.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_5_warcraft_2.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_6_ackley.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_6_diabetes.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_6_pressure.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_6_warcraft_1.sh"
  "bash scripts/scripts_cp/run_array_launcher_cp_6_warcraft_2.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_2_ackley.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_2_diabetes.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_2_pressure.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_2_warcraft_1.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_2_warcraft_2.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_3_ackley.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_3_diabetes.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_3_pressure.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_3_warcraft_1.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_3_warcraft_2.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_4_ackley.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_4_diabetes.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_4_pressure.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_4_warcraft_1.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_4_warcraft_2.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_5_ackley.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_5_diabetes.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_5_pressure.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_5_warcraft_1.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_5_warcraft_2.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_6_ackley.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_6_diabetes.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_6_pressure.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_6_warcraft_1.sh"
  "bash scripts/scripts_ring/run_array_launcher_ring_6_warcraft_2.sh"
  "bash scripts/scripts_train/run_array_launcher_train_2_ackley.sh"
  "bash scripts/scripts_train/run_array_launcher_train_2_diabetes.sh"
  "bash scripts/scripts_train/run_array_launcher_train_2_pressure.sh"
  "bash scripts/scripts_train/run_array_launcher_train_2_warcraft_1.sh"
  "bash scripts/scripts_train/run_array_launcher_train_2_warcraft_2.sh"
  "bash scripts/scripts_train/run_array_launcher_train_3_ackley.sh"
  "bash scripts/scripts_train/run_array_launcher_train_3_diabetes.sh"
  "bash scripts/scripts_train/run_array_launcher_train_3_pressure.sh"
  "bash scripts/scripts_train/run_array_launcher_train_3_warcraft_1.sh"
  "bash scripts/scripts_train/run_array_launcher_train_3_warcraft_2.sh"
  "bash scripts/scripts_train/run_array_launcher_train_4_ackley.sh"
  "bash scripts/scripts_train/run_array_launcher_train_4_diabetes.sh"
  "bash scripts/scripts_train/run_array_launcher_train_4_pressure.sh"
  "bash scripts/scripts_train/run_array_launcher_train_4_warcraft_1.sh"
  "bash scripts/scripts_train/run_array_launcher_train_4_warcraft_2.sh"
  "bash scripts/scripts_train/run_array_launcher_train_5_ackley.sh"
  "bash scripts/scripts_train/run_array_launcher_train_5_diabetes.sh"
  "bash scripts/scripts_train/run_array_launcher_train_5_pressure.sh"
  "bash scripts/scripts_train/run_array_launcher_train_5_warcraft_1.sh"
  "bash scripts/scripts_train/run_array_launcher_train_5_warcraft_2.sh"
  "bash scripts/scripts_train/run_array_launcher_train_6_ackley.sh"
  "bash scripts/scripts_train/run_array_launcher_train_6_diabetes.sh"
  "bash scripts/scripts_train/run_array_launcher_train_6_pressure.sh"
  "bash scripts/scripts_train/run_array_launcher_train_6_warcraft_1.sh"
  "bash scripts/scripts_train/run_array_launcher_train_6_warcraft_2.sh"
  "bash scripts/scripts_gp/run_array_launcher_gp_ackley.sh"
  "bash scripts/scripts_gp/run_array_launcher_gp_diabetes.sh"
  "bash scripts/scripts_gp/run_array_launcher_gp_pressure.sh"
  "bash scripts/scripts_gp/run_array_launcher_gp_warcraft_1.sh"
  "bash scripts/scripts_gp/run_array_launcher_gp_warcraft_2.sh"
  "bash scripts/scripts_tpe/run_array_launcher_tpe_3_ackley.sh"
  "bash scripts/scripts_tpe/run_array_launcher_tpe_3_diabetes.sh"
  "bash scripts/scripts_tpe/run_array_launcher_tpe_3_pressure.sh"
  "bash scripts/scripts_tpe/run_array_launcher_tpe_3_warcraft_1.sh"
  "bash scripts/scripts_tpe/run_array_launcher_tpe_3_warcraft_2.sh"
  "bash scripts/scripts_nnmilp/run_array_launcher_nnmilp_ackley.sh"
  "bash scripts/scripts_nnmilp/run_array_launcher_nnmilp_diabetes.sh"
  "bash scripts/scripts_nnmilp/run_array_launcher_nnmilp_pressure.sh"
  "bash scripts/scripts_nnmilp/run_array_launcher_nnmilp_warcraft_1.sh"
  "bash scripts/scripts_nnmilp/run_array_launcher_nnmilp_warcraft_2.sh"
)

for cmd in "${commands[@]}"; do
  echo "---"
  echo "▶️  Executing: $cmd"
  eval $cmd
  echo "⏸️  Pausing for 2 seconds..."
  sleep 2
done

echo "---"
echo "✅ All commands finished."