python3 create.py 7 diabetes
python3 create.py 8 diabetes
python3 create.py 9 diabetes
python3 create.py 10 diabetes
python3 create.py 11 diabetes
python3 create.py 12 diabetes
python3 create.py 13 diabetes
python3 create.py 14 diabetes
python3 create.py 15 diabetes
