# bash scripts_train/run_array_launcher_train_2_ackley.sh
# bash scripts_train/run_array_launcher_train_2_diabetes.sh
# bash scripts_train/run_array_launcher_train_2_pressure.sh
bash scripts_train/run_array_launcher_train_2_warcraft_1.sh
bash scripts_train/run_array_launcher_train_2_warcraft_2.sh

# bash scripts_train/run_array_launcher_train_3_ackley.sh
# bash scripts_train/run_array_launcher_train_3_diabetes.sh
# bash scripts_train/run_array_launcher_train_3_pressure.sh
# bash scripts_train/run_array_launcher_train_3_warcraft_1.sh
# bash scripts_train/run_array_launcher_train_3_warcraft_2.sh

# bash scripts_train/run_array_launcher_train_4_ackley.sh
# bash scripts_train/run_array_launcher_train_4_diabetes.sh
# bash scripts_train/run_array_launcher_train_4_pressure.sh
# bash scripts_train/run_array_launcher_train_4_warcraft_1.sh
# bash scripts_train/run_array_launcher_train_4_warcraft_2.sh

# bash scripts_train/run_array_launcher_train_5_ackley.sh
# bash scripts_train/run_array_launcher_train_5_diabetes.sh
# bash scripts_train/run_array_launcher_train_5_pressure.sh
# bash scripts_train/run_array_launcher_train_5_warcraft_1.sh
# bash scripts_train/run_array_launcher_train_5_warcraft_2.sh

# bash scripts_train/run_array_launcher_train_6_ackley.sh
# bash scripts_train/run_array_launcher_train_6_diabetes.sh
# bash scripts_train/run_array_launcher_train_6_pressure.sh
# bash scripts_train/run_array_launcher_train_6_warcraft_1.sh
# bash scripts_train/run_array_launcher_train_6_warcraft_2.sh