# bash scripts_train/run_array_launcher_train_2_ackley.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_2_diabetes.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_2_pressure.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_2_warcraft_1.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_2_warcraft_2.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_3_ackley.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_3_diabetes.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_3_pressure.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_3_warcraft_1.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_3_warcraft_2.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_4_ackley.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_4_diabetes.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_4_pressure.sh 
# sleep 2
# bash scripts_train/run_array_launcher_train_4_warcraft_1.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_4_warcraft_2.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_5_ackley.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_5_diabetes.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_5_pressure.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_5_warcraft_1.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_5_warcraft_2.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_6_ackley.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_6_diabetes.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_6_pressure.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_6_warcraft_1.sh
# sleep 2
# bash scripts_train/run_array_launcher_train_6_warcraft_2.sh
# sleep 2

# bash scripts_ring/run_array_launcher_ring_2_ackley.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_2_diabetes.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_2_pressure.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_2_warcraft_1.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_2_warcraft_2.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_3_ackley.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_3_diabetes.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_3_pressure.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_3_warcraft_1.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_3_warcraft_2.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_4_ackley.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_4_diabetes.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_4_pressure.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_4_warcraft_1.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_4_warcraft_2.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_5_ackley.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_5_diabetes.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_5_pressure.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_5_warcraft_1.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_5_warcraft_2.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_6_ackley.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_6_diabetes.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_6_pressure.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_6_warcraft_1.sh
# sleep 2
# bash scripts_ring/run_array_launcher_ring_6_warcraft_2.sh
# sleep 2

# bash scripts_cp/run_array_launcher_cp_2_ackley.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_2_diabetes.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_2_pressure.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_2_warcraft_1.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_2_warcraft_2.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_3_ackley.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_3_diabetes.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_3_pressure.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_3_warcraft_1.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_3_warcraft_2.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_4_ackley.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_4_diabetes.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_4_pressure.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_4_warcraft_1.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_4_warcraft_2.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_5_ackley.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_5_diabetes.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_5_pressure.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_5_warcraft_1.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_5_warcraft_2.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_6_ackley.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_6_diabetes.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_6_pressure.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_6_warcraft_1.sh
# sleep 2
# bash scripts_cp/run_array_launcher_cp_6_warcraft_2.sh
# sleep 2

# bash scripts_nnmilp/run_array_launcher_nnmilp_ackley.sh
# sleep 2
# bash scripts_nnmilp/run_array_launcher_nnmilp_diabetes.sh
# sleep 2
# bash scripts_nnmilp/run_array_launcher_nnmilp_warcraft_1.sh
# sleep 2
# bash scripts_nnmilp/run_array_launcher_nnmilp_warcraft_2.sh
# sleep 2
# bash scripts_nnmilp/run_array_launcher_nnmilp_pressure.sh
# sleep 2

# bash scripts_tpe/run_array_launcher_tpe_ackley.sh
# sleep 2
# bash scripts_tpe/run_array_launcher_tpe_diabetes.sh
# sleep 2
# bash scripts_tpe/run_array_launcher_tpe_warcraft_1.sh
# sleep 2
# bash scripts_tpe/run_array_launcher_tpe_warcraft_2.sh
# sleep 2
bash scripts_tpe/run_array_launcher_tpe_pressure.sh
sleep 2


# bash scripts_gp/run_array_launcher_gp_ackley.sh
# sleep 2
# bash scripts_gp/run_array_launcher_gp_diabetes.sh
# sleep 2
# bash scripts_gp/run_array_launcher_gp_warcraft_1.sh
# sleep 2
# bash scripts_gp/run_array_launcher_gp_warcraft_2.sh
# sleep 2
bash scripts_gp/run_array_launcher_gp_pressure.sh
sleep 2
