bash scripts_gp/run_array_launcher_nnmilp_ackley.sh
bash scripts_gp/run_array_launcher_nnmilp_diabetes.sh
bash scripts_gp/run_array_launcher_nnmilp_warcraft_1.sh
bash scripts_gp/run_array_launcher_nnmilp_warcraft_2.sh
bash scripts_gp/run_array_launcher_nnmilp_pressure.sh
