#!/bin/bash -l
python3 utils_dev/add_constraints.py results_tf_2_diabetes_complement_2
python3 utils_dev/add_constraints.py results_tf_4_diabetes_complement_2
python3 utils_dev/add_constraints.py results_tf_5_diabetes_complement_2
python3 utils_dev/add_constraints.py results_tf_6_diabetes_complement_2
