bash scripts_ring/run_array_launcher_ring_2_ackley.sh
bash scripts_ring/run_array_launcher_ring_2_diabetes.sh
bash scripts_ring/run_array_launcher_ring_2_pressure.sh
bash scripts_ring/run_array_launcher_ring_2_warcraft_1.sh
bash scripts_ring/run_array_launcher_ring_2_warcraft_2.sh

bash scripts_ring/run_array_launcher_ring_3_ackley.sh
bash scripts_ring/run_array_launcher_ring_3_diabetes.sh
bash scripts_ring/run_array_launcher_ring_3_pressure.sh
bash scripts_ring/run_array_launcher_ring_3_warcraft_1.sh
bash scripts_ring/run_array_launcher_ring_3_warcraft_2.sh

bash scripts_ring/run_array_launcher_ring_4_ackley.sh
bash scripts_ring/run_array_launcher_ring_4_diabetes.sh
bash scripts_ring/run_array_launcher_ring_4_pressure.sh
bash scripts_ring/run_array_launcher_ring_4_warcraft_1.sh
bash scripts_ring/run_array_launcher_ring_4_warcraft_2.sh

bash scripts_ring/run_array_launcher_ring_5_ackley.sh
bash scripts_ring/run_array_launcher_ring_5_diabetes.sh
bash scripts_ring/run_array_launcher_ring_5_pressure.sh
bash scripts_ring/run_array_launcher_ring_5_warcraft_1.sh
bash scripts_ring/run_array_launcher_ring_5_warcraft_2.sh

bash scripts_ring/run_array_launcher_ring_6_ackley.sh
bash scripts_ring/run_array_launcher_ring_6_diabetes.sh
bash scripts_ring/run_array_launcher_ring_6_pressure.sh
bash scripts_ring/run_array_launcher_ring_6_warcraft_1.sh
bash scripts_ring/run_array_launcher_ring_6_warcraft_2.sh